/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TopClientStatsDTO } from './topClientStats';
import { GlobalKpiDTO } from './globalKpi';
import { TopCommercialStatsDTO } from './topCommercialStats';


export interface DashboardStatsDTO { 
    kpi?: GlobalKpiDTO;
    topCommercials?: Array<TopCommercialStatsDTO>;
    topClients?: Array<TopClientStatsDTO>;
}

