/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Représente un type de déchet (ex: limaille, cendres)
 */
export interface NatureDTO { 
    /**
     * L\'identifiant de la nature (ex: \'1\', \'5\', \'11\')
     */
    id?: string;
    /**
     * Le nom (ex: or fonte simple)
     */
    libelle?: string;
    /**
     * Exemple (ex: composants métalliques or)
     */
    commentaire?: string | null;
}

