/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMetaDTO } from './pageMeta';
import { PhoneContactDTO } from './phoneContact';


/**
 * Page paginée de contacts téléphoniques
 */
export interface PhoneContactPageDTO { 
    meta: PageMetaDTO;
    items: Array<PhoneContactDTO>;
}

