/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneContactDTO } from './phoneContact';


/**
 * Contact métier avec identité (personne physique/morale) et jusqu\'à 3 numéros (références vers PhoneContact).
 */
export interface PhoneUserLiteDTO { 
    id?: string;
    firstname?: string | null;
    lastname?: string | null;
    denomination?: string | null;
    company?: string | null;
    phone?: PhoneContactDTO;
}

