/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhoneUserLiteDTO } from './phoneUserLite';


export interface PhoneLogDTO { 
    id?: string;
    forfaitMobile?: string;
    eventDate?: string;
    type?: string;
    direction?: string;
    appelant?: PhoneUserLiteDTO;
    destination?: PhoneUserLiteDTO;
    zoneClient?: string;
    callType?: string | null;
    durationSec?: number | null;
    quantityOctets?: number | null;
    costHt?: number | null;
}

