/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Lien entre un phone user MySAAMP et le cumul de CA_HM pour un mois et une année donnés. 
 */
export interface PhoneUserMonthlyCaHmDTO { 
    /**
     * Identifiant interne du phone user
     */
    phoneUserId: string;
    /**
     * Identifiant client MySAAMP (équivalent cl_ident en old DB)
     */
    mysaampIdClient: number;
    /**
     * Année de la statistique
     */
    annee: number;
    /**
     * Mois de la statistique
     */
    mois: number;
    /**
     * Cumul de CA_HM sur le mois
     */
    caHm: number;
    /**
     * Libellé lisible du phone user / client
     */
    label?: string;
}

