/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DEPRECATED: phone_contact ne porte plus d\'identité (firstname/lastname/company/label). Utiliser PhoneUserUpsertRequest.
 */
export interface PhoneContactUpdateRequestDTO { 
    /**
     * Optionnel: si vous autorisez la correction du numéro (attention historique).
     */
    phoneNumber?: string | null;
}

