/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Référence de numéro de téléphone (historique). Contient uniquement l’identifiant et le numéro.
 */
export interface PhoneContactDTO { 
    id: string;
    phoneNumber: string;
}

