/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Entrée d\'historique d\'import de fichier
 */
export interface PhoneLogImportHistoryDTO { 
    id: string;
    fileName: string;
    /**
     * Empreinte SHA-256
     */
    checksum: string;
    sizeBytes: number;
    importedAt: string;
    /**
     * IN_PROGRESS
     */
    status: string;
    message?: string | null;
}

