/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Résultat de l\'import de fichiers CSV de logs téléphoniques
 */
export interface PhoneLogImportResultDTO { 
    /**
     * Nombre de fichiers reçus
     */
    fileCount: number;
    /**
     * Nombre total de lignes lues
     */
    totalRows: number;
    /**
     * Nombre de lignes importées
     */
    importedRows: number;
    /**
     * Liste des erreurs rencontrées
     */
    errors: Array<string>;
}

