/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Une seule ligne/tranche de prix dans une grille (basé sur _P_AFF et _F_DET)
 */
export interface PriceBreakDTO { 
    /**
     * ID de la ligne de prix (ex: 4048, 2653)
     */
    id?: number;
    pdsMin?: number;
    pdsMax?: number;
    prixBrutKg?: number;
    prixBrutMin?: number;
    pctAuPerteMin?: number | null;
    pdsAuPerteMinKg?: number | null;
    pdsAuPerteMinLot?: number | null;
    pctAuDecote?: number | null;
    pctAgPerteMin?: number | null;
    pdsAgPerteMinKg?: number | null;
    pdsAgPerteMinLot?: number | null;
    pctAgDecote?: number | null;
    pctPtPerteMin?: number | null;
    pdsPtPerteMinKg?: number | null;
    pdsPtPerteMinLot?: number | null;
    pctPtDecote?: number | null;
    pctPdPerteMin?: number | null;
    pdsPdPerteMinKg?: number | null;
    pdsPdPerteMinLot?: number | null;
    pctPdDecote?: number | null;
    pctRhPerteMin?: number | null;
    pdsRhPerteMinKg?: number | null;
    pdsRhPerteMinLot?: number | null;
    pctRhDecote?: number | null;
    pctIrPerteMin?: number | null;
    pdsIrPerteMinKg?: number | null;
    pdsIrPerteMinLot?: number | null;
    pctIrDecote?: number | null;
}

