/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PriceBreakDTO } from './priceBreak';


/**
 * Une grille de prix complète et éditable pour une règle
 */
export interface PriceGridDTO { 
    /**
     * ID de la règle parente (F ou P)
     */
    ruleId?: number;
    /**
     * Type de règle (F ou P)
     */
    ruleType?: PriceGridDTORuleTypeEnum;
    /**
     * Le code de liaison (ex: \'ASP1\', \'FSP1\', \'L301\')
     */
    ruleCode?: string;
    priceBreaks?: Array<PriceBreakDTO>;
}
export enum PriceGridDTORuleTypeEnum {
    FORFAIT = 'FORFAIT',
    PRESTATION = 'PRESTATION'
};



