/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalesRepKpiDTO } from './salesRepKpi';
import { SalesRepHourBucketDTO } from './salesRepHourBucket';


/**
 * Indicateurs détaillés d\'un commercial (forfaitContactId) sur une période.
 */
export interface SalesRepStatsDTO { 
    commercialId: string;
    startDate?: string | null;
    endDate?: string | null;
    kpi: SalesRepKpiDTO;
    activityByHour: Array<SalesRepHourBucketDTO>;
}

