/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Bucket d\'activité par heure (0..23).
 */
export interface SalesRepHourBucketDTO { 
    hour: number;
    /**
     * Nombre d\'appels (hors SMS) sur l\'heure
     */
    callCount: number;
    /**
     * Nombre de SMS sur l\'heure
     */
    smsCount: number;
    /**
     * Total interactions sur l\'heure
     */
    totalCount: number;
}

