/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Répartition des interactions (clients vs interne vs inconnu) sur la période.
 */
export interface SalesRepRatioDTO { 
    totalInteractions: number;
    clientInteractions: number;
    internalInteractions: number;
    unknownInteractions: number;
    /**
     * Pourcentage 0..100
     */
    clientPct: number;
    /**
     * Pourcentage 0..100
     */
    internalPct: number;
    /**
     * Pourcentage 0..100
     */
    unknownPct: number;
}

