/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SalesRepRatioDTO } from './salesRepRatio';


export interface SalesRepKpiDTO { 
    /**
     * Temps d\'appel cumulé en secondes
     */
    totalCallDurationSec: number;
    /**
     * Nombre d\'appels (hors SMS)
     */
    totalCalls: number;
    totalCallsWeekEndAndNight?: number;
    /**
     * Nombre de correspondants uniques (hors internes)
     */
    uniqueProspects: number;
    ratio: SalesRepRatioDTO;
}

