/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmsCorrespondentStatsDTO { 
    number: string;
    /**
     * Prénom issu de phone_user si disponible.
     */
    firstname?: string | null;
    /**
     * Nom issu de phone_user si disponible.
     */
    lastname?: string | null;
    /**
     * Company ou dénomination issue de phone_user si disponible.
     */
    company?: string | null;
    /**
     * Nom d\'affichage (si calculé côté API/front).
     */
    displayName?: string | null;
    smsCount: number;
    totalCostHt: number;
}

