/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export enum TarifBaseCategoryDTO {
    BASE_OR = 'BASE_OR',
    BASE_OR_ARGENT = 'BASE_OR_ARGENT',
    BASE_OR_PLATINOIDE = 'BASE_OR_PLATINOIDE',
    BASE_OR_ARGENT_PLATINOIDE = 'BASE_OR_ARGENT_PLATINOIDE',
    BASE_ARGENT = 'BASE_ARGENT',
    BASE_ARGENT_PLATINOIDE = 'BASE_ARGENT_PLATINOIDE',
    BASE_PLATINOIDE = 'BASE_PLATINOIDE',
    AUTRE = 'AUTRE'
}

