/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Détail des tarifs d\'affinage \'P\' (par poids).
 */
export interface TarifAffinagePAffDTO { 
    id?: number;
    codeTarifPAff?: string;
    pacThirdId?: number | null;
    pdsMin?: number;
    pdsMax?: number;
    prixBrutKg?: number;
    prixBrutMin?: number;
    pctAuPerteMin?: number;
    pdsAuPerteMinKg?: number;
    pdsAuPerteMinLot?: number;
    pctAgPerteMin?: number;
    pdsAgPerteMinKg?: number;
    pdsAgPerteMinLot?: number;
    pctPtPerteMin?: number;
    pdsPtPerteMinKg?: number;
    pdsPtPerteMinLot?: number;
    pctPdPerteMin?: number;
    pdsPdPerteMinKg?: number;
    pdsPdPerteMinLot?: number;
    pctRhPerteMin?: number;
    pdsRhPerteMinKg?: number;
    pdsRhPerteMinLot?: number;
    pctIrPerteMin?: number;
    pdsIrPerteMinKg?: number;
    pdsIrPerteMinLot?: number;
    commentaire?: string | null;
    dateCreation?: string;
    idCreation?: string;
    dateModification?: string | null;
    idModification?: string | null;
}

