/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tarif \'F\' (par % métaux).
 */
export interface TarifAffinageFDTO { 
    id?: number;
    dicGcoAttributeFree06Id?: string;
    codeTarif?: string;
    pctAuMin?: number;
    pctAuMax?: number;
    pctAgMin?: number;
    pctAgMax?: number;
    pctPtMin?: number;
    pctPtMax?: number;
    pctPdMin?: number;
    pctPdMax?: number;
    pctRhMin?: number;
    pctRhMax?: number;
    pctIrMin?: number;
    pctIrMax?: number;
    commentaire?: string | null;
    dateCreation?: string;
    idCreation?: string;
    dateModification?: string | null;
    idModification?: string | null;
}

