/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TarifBaseCategoryDTO } from './tarifBaseCategory';


export interface TarifRuleDTO { 
    id?: number;
    natureId?: string;
    ruleType?: TarifRuleDTORuleTypeEnum;
    baseCategory?: TarifBaseCategoryDTO;
    description?: string;
    codeTarifForfait?: string;
    codeTarifAffinage?: string;
    codeTarifAnalyse?: string;
    codeTarifFonte?: string;
    codeTarifPreparation?: string;
    pctAuMin?: number;
    pctAuMax?: number;
    pctAgMin?: number;
    pctAgMax?: number;
    pctPtMin?: number;
    pctPtMax?: number;
    pctPdMin?: number;
    pctPdMax?: number;
    pctRhMin?: number;
    pctRhMax?: number;
    pctIrMin?: number;
    pctIrMax?: number;
}
export enum TarifRuleDTORuleTypeEnum {
    FORFAIT = 'FORFAIT',
    PRESTATION = 'PRESTATION'
};



