/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Détail des tarifs d\'homogénéisation \'P\' (par poids).
 */
export interface TarifAffinagePHomDTO { 
    id?: number;
    codeTarifPHom?: string;
    pacThirdId?: number | null;
    pdsMin?: number;
    pdsMax?: number;
    prixBrutKg?: number;
    prixBrutMin?: number;
    commentaire?: string | null;
    dateCreation?: string;
    idCreation?: string;
    dateModification?: string | null;
    idModification?: string | null;
}

