/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TarifAffinagePAffDTO } from './tarifAffinagePAff';
import { TarifAffinagePAnaDTO } from './tarifAffinagePAna';
import { TarifAffinagePPreDTO } from './tarifAffinagePPre';
import { TarifAffinagePHomDTO } from './tarifAffinagePHom';


/**
 * Réponse composite contenant les détails des tarifs \'P\' (affinage, analyse, etc.)
 */
export interface TarifsPDetailsResponseDTO { 
    affinage?: Array<TarifAffinagePAffDTO>;
    analyse?: Array<TarifAffinagePAnaDTO>;
    homogeneisation?: Array<TarifAffinagePHomDTO>;
    preparation?: Array<TarifAffinagePPreDTO>;
}

