/**
 * Saamp Web API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserSyncResponseDTO { 
    success?: boolean;
    message?: string;
    /**
     * Nombre d\'utilisateurs créés ou mis à jour
     */
    usersProcessed?: number;
    /**
     * Nombre de lignes ignorées (car c\'étaient des groupes)
     */
    groupsIgnored?: number;
}

